# -*- coding: utf-8 -*-
"""Technipen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16mdusfkg3jRhDtelXz6P_pRgMTsIdKVG

## Plotting Midpoints Between Original Data Points
"""

import matplotlib.pyplot as plt

# Original points
x = [1, 2, 3, 4, 5]
y = [2, 3, 5, 4, 6]

# Calculate midpoints
mid_x = []
mid_y = []

for i in range(len(x) - 1):
    new_x = (x[i] + x[i+1]) / 2
    new_y = (y[i] + y[i+1]) / 2
    mid_x.append(new_x)
    mid_y.append(new_y)

# Create a new plot with only the midpoints
plt.figure(figsize=(8, 6))
plt.scatter(mid_x, mid_y, color='green', marker='o', s=100, label='Midpoints')

plt.title('Midpoints Between Original Data Points')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.grid(True)
plt.legend()
plt.show()

"""## Detailed Midpoint Calculation and Plot (Blue, Green, Orange, Red Points)"""

import matplotlib.pyplot as plt
import math # For distance calculation

# Original points (blue dots)
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = [2, 3, 5, 4, 6, 7, 6, 8, 9, 11]

# 1. Calculate midpoints of original points (green dots)
mid_x = []
mid_y = []
for i in range(len(x) - 1):
    mid_x.append((x[i] + x[i+1]) / 2)
    mid_y.append((y[i] + y[i+1]) / 2)

# 2. Calculate midpoints of the green dots (mid_mid_points)
mid_mid_x = []
mid_mid_y = []
for i in range(len(mid_x) - 1):
    mid_mid_x.append((mid_x[i] + mid_x[i+1]) / 2)
    mid_mid_y.append((mid_y[i] + mid_y[i+1]) / 2)

# Helper function to find the closest original blue point to a given point
def find_closest_blue_point(px, py, all_x, all_y):
    min_dist = float('inf')
    closest_bx, closest_by = None, None
    for i in range(len(all_x)):
        dist = math.sqrt((all_x[i] - px)**2 + (all_y[i] - py)**2)
        if dist < min_dist:
            min_dist = dist
            closest_bx, closest_by = all_x[i], all_y[i]
    return closest_bx, closest_by

# 3. Calculate final_mid_x and final_mid_y (red x's)
# Each red x is the midpoint between a mid_mid_point and its closest original blue point.
final_mid_x = []
final_mid_y = []
for i in range(len(mid_mid_x)):
    mm_x, mm_y = mid_mid_x[i], mid_mid_y[i]

    # Find the closest original blue point to this mid_mid_point
    closest_bx, closest_by = find_closest_blue_point(mm_x, mm_y, x, y)

    # Calculate the red x (final midpoint)
    final_mid_x.append((mm_x + closest_bx) / 2)
    final_mid_y.append((mm_y + closest_by) / 2)

print(f"Calculated final_mid_x: {final_mid_x}")
print(f"Calculated final_mid_y: {final_mid_y}")

# --- Plotting ---
plt.figure(figsize=(10, 8))

# Plot original points (blue)
plt.scatter(x, y, color='blue', marker='o', s=50, label='Original Points')

# Plot midpoints of original points (green dots)
plt.scatter(mid_x, mid_y, color='green', marker='o', s=100, label='Midpoints of Original Points')

# Optional: Plot the mid_mid_points themselves for clarity
plt.scatter(mid_mid_x, mid_mid_y, color='orange', marker='s', s=80, alpha=0.7, label='Midpoints of Green Dots (Mid-Midpoints)')

# Plot the final midpoints (red x's)
plt.scatter(final_mid_x, final_mid_y, color='red', marker='x', s=150, label='Final Midpoints (Red X)')

# Plot lines connecting mid_mid_points (orange squares) to final_mid_points (red x's)
# This visually represents the calculation of the red x's.
for i in range(len(final_mid_x)):
    plt.plot([mid_mid_x[i], final_mid_x[i]], [mid_mid_y[i], final_mid_y[i]],
             color='purple', linestyle='--', linewidth=1, alpha=0.7,
             label='Mid-Midpoint to Final Midpoint Connections' if i == 0 else '_nolegend_')

plt.title('All Points: Original, Midpoints, Mid-Midpoints, and Final Midpoints')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.grid(True)
plt.legend()
plt.show()

"""## Line Graph of Merged Green Midpoints and Red Final Midpoints"""

import matplotlib.pyplot as plt
import math # For distance calculation

# Original points (blue dots)
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = [2, 3, 5, 4, 6, 7, 6, 8, 9, 11]

# 1. Calculate midpoints of original points (green dots)
mid_x = []
mid_y = []
for i in range(len(x) - 1):
    mid_x.append((x[i] + x[i+1]) / 2)
    mid_y.append((y[i] + y[i+1]) / 2)

# 2. Calculate midpoints of the green dots (mid_mid_points)
mid_mid_x = []
mid_mid_y = []
for i in range(len(mid_x) - 1):
    mid_mid_x.append((mid_x[i] + mid_x[i+1]) / 2)
    mid_mid_y.append((mid_y[i] + mid_y[i+1]) / 2)

# Helper function to find the closest original blue point to a given point
def find_closest_blue_point(px, py, all_x, all_y):
    min_dist = float('inf')
    closest_bx, closest_by = None, None
    for i in range(len(all_x)):
        dist = math.sqrt((all_x[i] - px)**2 + (all_y[i] - py)**2)
        if dist < min_dist:
            min_dist = dist
            closest_bx, closest_by = all_x[i], all_y[i]
    return closest_bx, closest_by

# 3. Calculate final_mid_x and final_mid_y (red x's)
# Each red x is the midpoint between a mid_mid_point and its closest original blue point.
final_mid_x = []
final_mid_y = []
for i in range(len(mid_mid_x)):
    mm_x, mm_y = mid_mid_x[i], mid_mid_y[i]

    # Find the closest original blue point to this mid_mid_point
    closest_bx, closest_by = find_closest_blue_point(mm_x, mm_y, x, y)

    # Calculate the red x (final midpoint)
    final_mid_x.append((mm_x + closest_bx) / 2)
    final_mid_y.append((mm_y + closest_by) / 2)

print(f"Calculated final_mid_x: {final_mid_x}")
print(f"Calculated final_mid_y: {final_mid_y}")

# --- Plotting ---
plt.figure(figsize=(10, 8))

# Combine the green dots (mid_x, mid_y) and red x's (final_mid_x, final_mid_y)
# into a single list of (x, y) tuples.
combined_points = []
for i in range(len(mid_x)):
    combined_points.append((mid_x[i], mid_y[i]))
for i in range(len(final_mid_x)):
    combined_points.append((final_mid_x[i], final_mid_y[i]))

# Sort all combined points by their x-coordinate to create a coherent line graph
combined_points.sort(key=lambda p: p[0])

# Separate sorted x and y values for plotting
sorted_combined_x = [p[0] for p in combined_points]
sorted_combined_y = [p[1] for p in combined_points]

# Plot the combined points as a line graph
plt.plot(sorted_combined_x, sorted_combined_y, color='green', marker='o', linestyle='-', label='Merged Green Midpoints and Red Final Midpoints')

plt.title('Combined Green Midpoints and Red Final Midpoints as Line Graph')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.grid(True)
plt.legend()
plt.show()

"""## Comparison: Original Points vs. Merged Midpoints (Line Graphs)"""

import matplotlib.pyplot as plt

# The x, y, sorted_combined_x, and sorted_combined_y variables are taken from the kernel state
# from the previous cell executions.

plt.figure(figsize=(10, 8))

# Plot the original points as a blue line
plt.plot(x, y, color='blue', marker='o', linestyle='-', label='Original Points (x, y)')

# Plot the combined green midpoints and red final midpoints as a green line
plt.plot(sorted_combined_x, sorted_combined_y, color='green', marker='o', linestyle='-', label='Merged Midpoints and Final Midpoints')

plt.title('Comparison: Original Points vs. Merged Midpoints as Lines')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.grid(True)
plt.legend()
plt.show()

"""## Tunable Smoothing with Alpha Factor"""

import matplotlib.pyplot as plt
import math # For distance calculation

# Original points (blue dots)
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = [2, 3, 5, 4, 6, 7, 6, 8, 9, 11]

# 1. Calculate midpoints of original points (green dots)
mid_x = []
mid_y = []
for i in range(len(x) - 1):
    mid_x.append((x[i] + x[i+1]) / 2)
    mid_y.append((y[i] + y[i+1]) / 2)

# 2. Calculate midpoints of the green dots (mid_mid_points)
mid_mid_x = []
mid_mid_y = []
for i in range(len(mid_x) - 1):
    mid_mid_x.append((mid_x[i] + mid_x[i+1]) / 2)
    mid_mid_y.append((mid_y[i] + mid_y[i+1]) / 2)

# Helper function to find the closest original blue point to a given point
def find_closest_blue_point(px, py, all_x, all_y):
    min_dist = float('inf')
    closest_bx, closest_by = None, None
    for i in range(len(all_x)):
        dist = math.sqrt((all_x[i] - px)**2 + (all_y[i] - py)**2)
        if dist < min_dist:
            min_dist = dist
            closest_bx, closest_by = all_x[i], all_y[i]
    return closest_bx, closest_by

# --- Smoothing Factor ---
# Define the smoothing factor (alpha) 0 <= alpha <= 1
# alpha = 0: final = mid_mid (no smoothing towards original points)
# alpha = 1: final = closest_original (full smoothing towards original points)
# alpha = 0.5: final = (mid_mid + closest_original) / 2 (equal average)
alpha = 0.5 # You can change this value to tune the smoothing

# 3. Calculate final_mid_x and final_mid_y (red x's) with smoothing
# Each red x is calculated using the smoothing factor.
final_mid_x = []
final_mid_y = []
for i in range(len(mid_mid_x)):
    mm_x, mm_y = mid_mid_x[i], mid_mid_y[i]

    # Find the closest original blue point to this mid_mid_point
    closest_bx, closest_by = find_closest_blue_point(mm_x, mm_y, x, y)

    # Calculate the red x (final midpoint) using the smoothing factor
    smoothed_x = (1 - alpha) * mm_x + alpha * closest_bx
    smoothed_y = (1 - alpha) * mm_y + alpha * closest_by
    final_mid_x.append(smoothed_x)
    final_mid_y.append(smoothed_y)

print(f"Calculated final_mid_x (with alpha={alpha}): {final_mid_x}")
print(f"Calculated final_mid_y (with alpha={alpha}): {final_mid_y}")

# --- Plotting ---
plt.figure(figsize=(10, 8))

# Combine the green dots (mid_x, mid_y) and red x's (final_mid_x, final_mid_y)
# into a single list of (x, y) tuples.
combined_points = []
for i in range(len(mid_x)):
    combined_points.append((mid_x[i], mid_y[i]))
for i in range(len(final_mid_x)):
    combined_points.append((final_mid_x[i], final_mid_y[i]))

# Sort all combined points by their x-coordinate to create a coherent line graph
combined_points.sort(key=lambda p: p[0])

# Separate sorted x and y values for plotting
sorted_combined_x = [p[0] for p in combined_points]
sorted_combined_y = [p[1] for p in combined_points]

# Plot the combined points as a line graph
plt.plot(sorted_combined_x, sorted_combined_y, color='green', marker='o', linestyle='-', label=f'Merged Green Midpoints and Smoothed Final Midpoints (alpha={alpha})')

plt.title('Combined Green Midpoints and Smoothed Final Midpoints as Line Graph')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.grid(True)
plt.legend()
plt.show()

"""## Savitzky-Golay Smoothing (100 Points, Double Pass)"""

import matplotlib.pyplot as plt
import numpy as np # For numerical operations
from scipy.signal import savgol_filter # For Savitzky-Golay filter

# Generate a larger and more 'vigorous' dataset
num_points = 100
x = np.linspace(0, 10, num_points)
# Create a trend (e.g., sine wave) and add significant random noise
y = np.sin(x * 1.5) * 5 + np.cos(x * 0.8) * 3 + np.random.normal(0, 2, num_points) + x * 0.5

# --- Tunable Smoothing Algorithm: Savitzky-Golay Filter ---
# Parameters for the Savitzky-Golay filter
# window_length: The length of the filter window (i.e., the number of coefficients). Must be an odd integer.
# polyorder: The order of the polynomial used to fit the samples. Must be less than window_length.

# You can tune these values:
window_length = 11  # Increased for larger dataset (must be odd)
polyorder = 3       # Example: 3rd order polynomial

# Ensure window_length is odd and less than the number of points
if window_length % 2 == 0:
    window_length += 1 # Make it odd
if window_length > len(y):
    window_length = len(y) if len(y) % 2 == 1 else len(y) - 1 # Adjust if too long
if polyorder >= window_length:
    polyorder = window_length - 1

# Apply the Savitzky-Golay filter to smooth the y data (first pass)
y_smoothed_1 = savgol_filter(y, window_length, polyorder)

# Apply the Savitzky-Golay filter to the first smoothed data (second pass)
y_smoothed_2 = savgol_filter(y_smoothed_1, window_length, polyorder)

print(f"Savitzky-Golay Smoothing with window_length={window_length}, polyorder={polyorder}")
print(f"Original Y (first 5): {y[:5].tolist()}")
print(f"First Smoothed Y (first 5): {y_smoothed_1[:5].tolist()}")
print(f"Second Smoothed Y (first 5): {y_smoothed_2[:5].tolist()}")

# --- Plotting ---
plt.figure(figsize=(12, 7))

# Plot original points
plt.scatter(x, y, color='blue', marker='.', s=50, label='Original Points (Vigorous)')

# Plot first smoothed line
plt.plot(x, y_smoothed_1, color='red', linestyle='-', linewidth=2, label=f'1st Savitzky-Golay Smoothed (window={window_length}, poly={polyorder})')

# Plot second smoothed line
plt.plot(x, y_smoothed_2, color='orange', linestyle='--', linewidth=2, label=f'2nd Savitzky-Golay Smoothed (on 1st Smoothed Data)')

plt.title('Savitzky-Golay Smoothing of a Vigorous Dataset (Double Pass)')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.grid(True)
plt.legend()
plt.show()

"""## Savitzky-Golay Smoothing (30 Points, Double Pass)"""

import matplotlib.pyplot as plt
import numpy as np # For numerical operations
from scipy.signal import savgol_filter # For Savitzky-Golay filter

# Generate a smaller and vigorous dataset
num_points = 30 # Changed to 30 points as requested
x = np.linspace(0, 10, num_points)
# Create a trend (e.g., sine wave) and add significant random noise
y = np.sin(x * 1.5) * 5 + np.cos(x * 0.8) * 3 + np.random.normal(0, 2, num_points) + x * 0.5

# --- Tunable Smoothing Algorithm: Savitzky-Golay Filter ---
# Parameters for the Savitzky-Golay filter
# window_length: The length of the filter window (i.e., the number of coefficients). Must be an odd integer.
# polyorder: The order of the polynomial used to fit the samples. Must be less than window_length.

# You can tune these values:
window_length = 11  # Keeping window_length as 11, but it might be too large for 30 points
polyorder = 3       # Keeping polyorder as 3

# Ensure window_length is odd and less than the number of points
if window_length % 2 == 0:
    window_length += 1 # Make it odd
# Adjust window_length if it's too large for the new num_points
if window_length > len(y):
    window_length = len(y) if len(y) % 2 == 1 else len(y) - 1 # Adjust if too long
if polyorder >= window_length:
    polyorder = window_length - 1

# Apply the Savitzky-Golay filter to smooth the y data (first pass)
y_smoothed_1 = savgol_filter(y, window_length, polyorder)

# Apply the Savitzky-Golay filter to the first smoothed data (second pass)
y_smoothed_2 = savgol_filter(y_smoothed_1, window_length, polyorder)

print(f"Savitzky-Golay Smoothing with window_length={window_length}, polyorder={polyorder}")
print(f"Original Y (first 5): {y[:5].tolist()}")
print(f"First Smoothed Y (first 5): {y_smoothed_1[:5].tolist()}")
print(f"Second Smoothed Y (first 5): {y_smoothed_2[:5].tolist()}")

# --- Plotting ---
plt.figure(figsize=(12, 7))

# Plot original points
plt.scatter(x, y, color='blue', marker='.', s=50, label='Original Points (Vigorous)')

# Plot first smoothed line
plt.plot(x, y_smoothed_1, color='red', linestyle='-', linewidth=2, label=f'1st Savitzky-Golay Smoothed (window={window_length}, poly={polyorder})')

# Plot second smoothed line
plt.plot(x, y_smoothed_2, color='orange', linestyle='--', linewidth=2, label=f'2nd Savitzky-Golay Smoothed (on 1st Smoothed Data)')

plt.title('Savitzky-Golay Smoothing of a Vigorous Dataset (Double Pass) - 30 Points')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.grid(True)
plt.legend()
plt.show()

"""## One-Euro Filter Class Definition"""

import math

class OneEuroFilter:
    def __init__(self, freq=120.0, min_cutoff=1.0, beta=0.0, d_cutoff=1.0):
        # 1 & 2. Initialize parameters
        self.freq = freq  # Frequency of the data (Hz)
        self.min_cutoff = min_cutoff  # Low-pass filter parameter for slow changes
        self.beta = beta  # Trade-off between latency and noise reduction
        self.d_cutoff = d_cutoff  # Parameter for filtering the derivative

        # 3. Initialize internal state variables
        self._x_prev = None  # Previously filtered value
        self._dx_prev = None  # Previously filtered derivative
        self._t_prev = None  # Previous timestamp

    # 4. Implement _alpha helper method
    @staticmethod
    def _alpha(cutoff, freq):
        if freq == 0:
            return 1.0  # Avoid division by zero, effectively no filtering if freq is 0
        tau = 1.0 / (2 * math.pi * cutoff)
        alpha = 1.0 / (1.0 + tau * freq)
        return alpha

    # 7. Implement _low_pass_filter helper method
    def _low_pass_filter(self, value, prev_value, alpha):
        if prev_value is None:
            return value
        return alpha * value + (1.0 - alpha) * prev_value

    # 5 & 6. Implement the main filtering method
    def __call__(self, timestamp, value):
        if self._t_prev is None:
            # First data point, initialize state and return raw value
            self._t_prev = timestamp
            self._x_prev = value
            self._dx_prev = 0.0 # Initial derivative is 0
            return value

        # Calculate time difference and update frequency
        dt = timestamp - self._t_prev
        # Ensure dt is not zero to avoid division by zero for frequency calculation
        if dt == 0:
            return self._x_prev # If no time has passed, return the previous filtered value

        self.freq = 1.0 / dt

        # Calculate raw derivative
        dx = (value - self._x_prev) / dt

        # Filter the derivative
        alpha_d = self._alpha(self.d_cutoff, self.freq)
        dx_filtered = self._low_pass_filter(dx, self._dx_prev, alpha_d)

        # Calculate effective cutoff for signal filter
        effective_cutoff = self.min_cutoff + self.beta * abs(dx_filtered)

        # Filter the signal
        alpha_x = self._alpha(effective_cutoff, self.freq)
        x_filtered = self._low_pass_filter(value, self._x_prev, alpha_x)

        # Update internal state variables
        self._x_prev = x_filtered
        self._dx_prev = dx_filtered
        self._t_prev = timestamp

        return x_filtered

print("OneEuroFilter class defined.")

"""## Simulate Noisy Data for One-Euro Filter"""

import numpy as np

# 1. Parameters for data generation
num_iterations = 100
dt = 0.1 # Time step between data points

# 2. Create lists to store simulated data
timestamps = []
raw_values = []

# 3. Iterate to generate individual data points
for i in range(num_iterations):
    # a. Calculate timestamp
    current_timestamp = i * dt
    timestamps.append(current_timestamp)

    # b. Generate raw_value with a base signal (sine wave) and random noise
    # Example: y = A * sin(B*t) + C * t + noise
    base_signal = 10 * np.sin(current_timestamp * 0.5) + 2 * current_timestamp
    noise = np.random.normal(0, 1.5) # Mean 0, standard deviation 1.5
    current_raw_value = base_signal + noise
    raw_values.append(current_raw_value)

# 4. Print the first few generated timestamps and raw_values
print(f"First 5 timestamps: {timestamps[:5]}")
print(f"First 5 raw_values: {raw_values[:5]}")
print(f"Total data points generated: {len(timestamps)}")

"""## Apply One-Euro Filter to Simulated Data"""

import numpy as np

# Initialize the OneEuroFilter
# You can tune these parameters based on your desired smoothing and responsiveness
# freq: estimated frequency of incoming data (1/dt)
# min_cutoff: lower cutoff frequency (higher value -> more aggressive smoothing of slow movements)
# beta: factor for dynamic cutoff (higher value -> more aggressive smoothing of fast movements)
# d_cutoff: cutoff frequency for the derivative filter

one_euro_filter = OneEuroFilter(freq=1.0/dt, min_cutoff=1.0, beta=0.01, d_cutoff=1.0)

# List to store filtered values
filtered_values = []

# Apply the filter to each simulated data point
for i in range(num_iterations):
    timestamp = timestamps[i]
    raw_value = raw_values[i]

    # Apply the filter
    filtered_value = one_euro_filter(timestamp, raw_value)
    filtered_values.append(filtered_value)

# Print the first few filtered values
print(f"First 5 filtered_values: {filtered_values[:5]}")
print(f"Total filtered data points: {len(filtered_values)}")

"""## Plot One-Euro Filter Raw vs. Filtered Data"""

import matplotlib.pyplot as plt

# Plotting the raw and filtered data
plt.figure(figsize=(12, 6))
plt.plot(timestamps, raw_values, label='Raw Data (Noisy)', alpha=0.7, color='blue')
plt.plot(timestamps, filtered_values, label='Filtered Data (OneEuroFilter)', color='red', linewidth=2)

plt.title('Raw vs. Filtered Data using OneEuroFilter')
plt.xlabel('Timestamp')
plt.ylabel('Value')
plt.grid(True)
plt.legend()
plt.show()

"""## Real-time One-Euro Filter Animation Setup"""

import matplotlib.pyplot as plt
import matplotlib.animation as animation
import numpy as np # Already imported, but good to include for clarity

# The OneEuroFilter class and dt are already defined from previous cells.
# one_euro_filter = OneEuroFilter(freq=1.0/dt, min_cutoff=1.0, beta=0.01, d_cutoff=1.0)

# Re-initialize the OneEuroFilter for the animation, as it maintains state
one_euro_filter_anim = OneEuroFilter(freq=1.0/dt, min_cutoff=1.0, beta=0.01, d_cutoff=1.0)

# Initialize lists to store data for animation
animation_timestamps = []
animation_raw_values = []
animation_filtered_values = []

# Set up the figure and axes
fig, ax = plt.subplots(figsize=(12, 6))
ax.set_title('Real-time OneEuroFilter Smoothing')
ax.set_xlabel('Timestamp')
ax.set_ylabel('Value')
ax.grid(True)

# Initialize two empty line objects for the plot
line_raw, = ax.plot([], [], 'b.', label='Raw Data') # 'b.' for blue dots
line_filtered, = ax.plot([], [], 'r-', linewidth=2, label='Filtered Data') # 'r-' for red line

# Set initial limits (will be adjusted dynamically)
ax.set_xlim(0, 10)
ax.set_ylim(-5, 15)

# Current iteration counter for data generation
current_iteration = 0

print("Setup for animation complete. Filter initialized, lists created, and plot elements defined.")

"""## Real-time One-Euro Filter Animation"""

num_iterations_anim = 200 # Total number of points to simulate for the animation

def update(frame):
    global current_iteration, one_euro_filter_anim

    if current_iteration >= num_iterations_anim:
        # Stop the animation if all data points are generated
        ani.event_source.stop()
        return line_raw, line_filtered

    # Generate a new timestamp and raw value
    current_timestamp = current_iteration * dt
    # Example: y = A * sin(B*t) + C * t + noise
    base_signal = 10 * np.sin(current_timestamp * 0.5) + 2 * current_timestamp
    noise = np.random.normal(0, 1.5) # Mean 0, standard deviation 1.5
    new_raw_value = base_signal + noise

    # Append to animation lists
    animation_timestamps.append(current_timestamp)
    animation_raw_values.append(new_raw_value)

    # Apply the OneEuroFilter
    filtered_value = one_euro_filter_anim(current_timestamp, new_raw_value)
    animation_filtered_values.append(filtered_value)

    # Update plot data
    line_raw.set_data(animation_timestamps, animation_raw_values)
    line_filtered.set_data(animation_timestamps, animation_filtered_values)

    # Adjust x-axis limits dynamically (e.g., show last 50 points or a fixed time window)
    # We'll make it expand initially, then slide
    if current_timestamp > 0:
        min_x = max(0, current_timestamp - 10) # Show last 10 units of time
        max_x = current_timestamp + 1 # Give a little buffer ahead
    else:
        min_x = 0
        max_x = 10
    ax.set_xlim(min_x, max_x)

    # Adjust y-axis limits dynamically
    if len(animation_raw_values) > 0:
        all_y_values = animation_raw_values + animation_filtered_values
        min_y = min(all_y_values) - 2 # Add some padding
        max_y = max(all_y_values) + 2 # Add some padding
        ax.set_ylim(min_y, max_y)

    current_iteration += 1
    return line_raw, line_filtered

# Create the animation
ani = animation.FuncAnimation(fig, update, frames=num_iterations_anim,
                              interval=dt*1000, blit=True, repeat=False)

# Add legend
ax.legend()

plt.show()

print("Real-time plotting with OneEuroFilter animation displayed.")